export const PUBLIC_ROUTES = [
    '/',
    '/tutor/sign-in',
    '/tutor/sign-up',
    '/tutor/landing-page',
    '/veterinary/sign-in',
    '/veterinary/sign-up',
    '/veterinary/landing-page',
    '/sign-in',
    '/sign-up',
    '/forgot-password',
    '/activation',
    '/logout',
    '/confirm-account',
]
