export const PUBLIC_ROUTES = [
    '/',
    '/tutor/sign-in',
    '/tutor/sign-up',
    '/tutor/landing-page',
    '/tutor/activation',
    '/veterinary/sign-in',
    '/veterinary/sign-up',
    '/veterinary/landing-page',
    '/veterinary/activation',
    '/sign-in',
    '/sign-up',
    '/forgot-password',
    '/confirm-account',
    '/privacy-policy',
    '/service-terms',
]
