export const sub_specialty = [
    {
        label: 'Anestesiologia e controle da dor',
        value: 'anesthesiology_and_pain_control',
    },
    { label: 'Cardiologia', value: 'cardiology' },
    { label: 'Cirurgias', value: 'surgeries' },
    { label: 'Dermatologia', value: 'dermatology' },
    { label: 'Endocrinologia', value: 'endocrinology' },
    { label: 'Felinos', value: 'feline' },
    {
        label: 'Gastroenterologia e Endoscopia',
        value: 'gastroenterology_and_endoscopy',
    },
    { label: 'Medicina Comportamental', value: 'behavioral_medicine' },
    { label: 'Nefrologia e Urologia', value: 'nephrology_and_urology' },
    { label: 'Neurologia', value: 'neurology' },
    { label: 'Nutrição Clínica', value: 'clinical_nutrition' },
    { label: 'Odontologia', value: 'dentistry' },
    { label: 'Oftalmologia', value: 'ophthalmology' },
    { label: 'Oncologia', value: 'oncology' },
    { label: 'Ortopedia', value: 'orthopedics' },
    { label: 'Pneumologia', value: 'pneumology' },
    { label: 'Reprodução e Neonatologia', value: 'reproduction_and_neonatology' },
    { label: 'Clinica Geral', value: 'general_clinic' },
]

export const Specialty = {
    anesthesiology_and_pain_control: 'Anestesiologia e controle da dor',
    cardiology: 'Cardiologia',
    surgeries: 'Cirurgias',
    dermatology: 'Dermatologia',
    endocrinology: 'Endocrinologia',
    feline: 'Felinos',
    gastroenterology_and_endoscopy: 'Gastroenterologia e Endoscopia',
    behavioral_medicine: 'Medicina Comportamental',
    nephrology_and_urology: 'Nefrologia e Urologia',
    neurology: 'Neurologia',
    clinical_nutrition: 'Nutrição Clínica',
    dentistry: 'Odontologia',
    ophthalmology: 'Oftalmologia',
    oncology: 'Oncologia',
    orthopedics: 'Ortopedia',
    pneumology: 'Pneumologia',
    reproduction_and_neonatology: 'Reprodução e Neonatologia',
    general_clinic: 'Clinica Geral',
} as const
export type KeysSpecialty = keyof typeof Specialty
