export const sub_specialty = [
    'Anestesiologia e controle da dor',
    'Cardiologia',
    'Cirurgias',
    'Dermatologia',
    'Endocrinologia',
    'Felinos',
    'Gastroenterologia e Endoscopia',
    'Medicina Comportamental',
    'Nefrologia e Urologia',
    'Neurologia',
    'Nutrição Clínica',
    'Odontologia',
    'Oftalmologia',
    'Oncologia',
    'Ortopedia',
    'Pneumologia',
    'Reprodução e Neonatologia',
    'Clinica Geral',
]
